name: Publish HELM chart

on:
  push:
    branches:
      - "main"
    paths:
      - "charts/**"
    paths-ignore:
      - "charts/**/*.md"

permissions:
  actions: read
  contents: write

concurrency:
  group: chart-publish-${{ github.ref }}
  cancel-in-progress: true

jobs:
  publish-helm-chart:
    name: Publish latest chart
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Publish HELM chart
        uses: stefanprodan/helm-gh-pages@v1.7.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          charts_dir: charts
